openapi: 3.0.3

info:
  version: 1.0.11
  title: "Cart Microservice Product service API"
  description: "Manages product inventory"
  contact:
    name: "AdeThorMiwa"
    email: "BenDaMyth@gmail.com"

x-service-id: "product"
x-organization: "rust"

tags:
  - name: product
paths:
  /products:
    get:
      security:
        - authToken: []
      tags:
        - "product"
      summary: "Fetch product list"
      operationId: getProductList
      x-visibility: public
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    authToken:
      type: apiKey
      name: "x-auth-token"
      in: header
