openapi: 3.0.3

info:
  version: 1.0.11
  title: "Cart Microservice Cart service API"
  description: "Manages user cart"
  contact:
    name: "AdeThorMiwa"
    email: "BenDaMyth@gmail.com"

x-service-id: "cart"

tags:
  - name: cart
paths:
  /cart:
    get:
      security:
        - authToken: []
      tags:
        - "cart"
      summary: "Fetch cart items"
      operationId: getCartItems
      x-visibility: public
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    authToken:
      type: apiKey
      name: "x-auth-token"
      in: header
