name: Trigger Workflow Dispatch

on:
  push:
    paths:
      - "**/*-spec.yaml"
      - "**/trigger.yaml"

jobs:
  send-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const { getSpecPaths } = require("./spec-path");
            const paths = await getSpecPaths();

            console.log(context)
              
            # await github.rest.actions.createWorkflowDispatch({
            #   owner: context.repo.owner,
            #   repo: 'rms-openapi',
            #   workflow_id: 'import-spec.yaml',
            #   ref: context.ref,
            #   inputs: {
            #     repo: `${context.repo.owner}/${context.repo.repo}`,
            #     ref: context.ref,
            #     paths: paths.split(/\n/).filter((p) => p.trim().length).join(",")
            #   }
            # })
